[tool.poetry]
name = "pyloxone_api"
version = "0.1.0"
description = "A package for interacting at a low(ish) level with a Loxone miniserver via the Loxone websocket API"
authors = ["Joachim Dehli", "Lawrence Akka"]
license = "Apache License 2.0"
exclude = ["pyloxone_api/lox_token.cfg"]

[tool.poetry.dependencies]
python = "^3.8"
requests-async = "^0.6.2"
pycryptodome = "^3.10.1"
websockets = "^9.0.1"

[tool.poetry.dev-dependencies]
black = "^21.5b1"
pytest = "^6.2.4"
pylint = "^2.8.2"
flake8 = "^3.9.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
